os: linux
dist: bionic
language: python
jobs:
  include:
    - name: Python 3.7 on Bionic
      python: 3.7

# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
install:
  - python setup.py develop

before_script:
  - pwd
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
script:
  - echo $BRANCH
  - pytest --cov-report term-missing --cov-config=.coveragerc --cov=requiam tests
  - export persist_path=$(pwd)
  - alias cmd_prefix='./scripts/script_run --config config/figshare.ini --persistent_path $persist_path --ldap_password $pass --grouper_password $pass'
  - eval cmd_prefix
