os: linux
dist: bionic
language: python
jobs:
  include:
    - name: Python 3.7 on Bionic
      python: 3.7

# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest pytest-cov
install:
  - python setup.py install

before_script:
  - pwd
  - ls -la
  - git log --oneline -n 5
  - git status
  - cat .git/HEAD
  - cat .git
  - ls -la .git/refs/heads/
script:
  pytest --ignore=tests/test_git_info.py --cov-report term-missing --cov-config=.coveragerc --cov=requiam tests
